stages:
  - test
  - build

image: node:20

variables:
  CONTENTFUL_SPACE_ID: $CONTENTFUL_SPACE_ID
  CONTENTFUL_ACCESS_TOKEN: $CONTENTFUL_ACCESS_TOKEN
  CONTENTFUL_PREVIEW_ACCESS_TOKEN: $CONTENTFUL_PREVIEW_ACCESS_TOKEN
  CONTENTFUL_PREVIEW_SECRET: $CONTENTFUL_PREVIEW_SECRET
  CONTENTFUL_REVALIDATE_SECRET: $CONTENTFUL_REVALIDATE_SECRET

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - cd mp1-contentfull-tdw
  - npm install

run_tests:
  stage: test
  script:
    - npm run lint
    - npm run prettier
    - npm test
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

build:
  stage: build
  script:
    - npm run build
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
